# Generated by Django 3.2.9 on 2023-08-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmsw', '0002_auto_20230829_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='param',
            name='category',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='param',
            name='desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='param',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='param',
            name='code',
            field=models.TextField(default='', max_length=75000),
        ),
    ]
